### ISSUE TITLE
Ray.so update

### ISSUE THREAD

**Issue by FSipiano** [artemnovichkov/RaySo#1]
Hey! Just thought you would want to know that we added the ability to configure the language in [ray.so](http://ray.so) via the URL query parameters. This means that you are able to parse a particular language into the URL and the site will render accordingly. 

You can already do this with other query parameters such as the colors and padding as well as the background and dark mode toggles, and we are excited to see what you will create with this new configurable parameter.

[Set-language-from-url.mp4.zip](https://github.com/ridarf/raythis/files/6235921/Set-language-from-url.mp4.zip)

All parameters can be found in [this script command](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/create-image-from-code.sh) 

Please reach out to me if you have any questions!

Faye

**Comment by artemnovichkov** [comment]
Hi, @FSipiano! Thanks for sharing! I'll add this parameter with auto detecting 🙂

**Comment by artemnovichkov** [comment]
Hello, @FSipiano! I've released a new version with language detection! Thanks again for the issue!

**Comment by FSipiano** [comment]
Awesome, thanks for the update!
